services:
  mediamtx:
    image: bluenviron/mediamtx:1.20.1
    container_name: mediamtx
    network_mode: host
    env_file:
      - .env
    environment:
      MTX_PATHS_CAMARA_SOURCE: rtsp://${CAMERA_USER}:${CAMERA_PASSWORD}@${CAMERA_IP}:554${CAMERA_RTSP_PATH}
    volumes:
      - ./mediamtx.yml:/mediamtx.yml:ro
    restart: unless-stopped
