services:
  go2rtc:
    image: alexxit/go2rtc
    container_name: go2rtc
    network_mode: host
    env_file:
      - .env
    volumes:
      - ./go2rtc.yaml:/config/go2rtc.yaml
    restart: unless-stopped
